<nav>
	<a href="index.php" title="Home page" class="btn">HOME</a>
	<a href="login.php" class="btn" title="Login for current users">LOGIN</a>
	<a href="register.php" class="btn" title="New user Registration">REGISTER</a>
	<a href="bookings.php" class="btn" title="Booking a cab services">BOOKINGS</a>
	<a href="admin.php" class="btn" title="Admin services">ADMIN</a>
	<a href="mailto:102005528@student.swin.edu.au" class="btn" title="Contact details" >Contact Us</a>
</nav>
